# Generated by Django 5.2.3 on 2025-06-17 17:44

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackTracePortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('Annually', 'Annually'), ('Monthly', 'Monthly'), ('Quarterly', 'Quarterly')])),
                ('assets', models.JSONField(validators=[api.models.validateAssets])),
            ],
        ),
    ]
