# Generated by Django 5.2.3 on 2025-08-09 00:02

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('ticker', models.TextField()),
                ('qty', models.IntegerField()),
                ('lastdividenddate', models.DateTimeField(blank=True, db_column='lastDividendDate', null=True)),
            ],
            options={
                'db_table': 'Assets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Papertradeaccount',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('balance', models.FloatField()),
            ],
            options={
                'db_table': 'PaperTradeAccount',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Papertradeorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.TextField()),
                ('ordertype', models.TextField(db_column='orderType')),
                ('side', models.TextField()),
                ('qty', models.IntegerField()),
                ('status', models.TextField()),
                ('submitted', models.DateTimeField()),
                ('orderprice', models.FloatField(blank=True, db_column='orderPrice', null=True)),
                ('limitprice', models.FloatField(blank=True, db_column='limitPrice', null=True)),
                ('stopprice', models.FloatField(blank=True, db_column='stopPrice', null=True)),
                ('trailprice', models.FloatField(blank=True, db_column='trailPrice', null=True)),
                ('trailrate', models.FloatField(blank=True, db_column='trailRate', null=True)),
                ('datelastchecked', models.DateTimeField(db_column='dateLastChecked')),
            ],
            options={
                'db_table': 'PaperTradeOrder',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('email', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'User',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MonthlyIndicatorData',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('lei', models.JSONField()),
                ('manufacturingpmi', models.JSONField(db_column='ManufacturingPmi')),
                ('servicespmi', models.JSONField(db_column='servicesPmi')),
            ],
        ),
        migrations.CreateModel(
            name='TradeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(validators=[api.models.check_if_valid_ticker])),
                ('qty', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('order_type', models.CharField(choices=[('Market', 'Market'), ('Limit', 'Limit'), ('Stop', 'Stop'), ('Stop Limit', 'Stop Limit'), ('Trailing Stop', 'Trailing Stop')])),
                ('side', models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')])),
                ('time_in_force', models.CharField(choices=[('DAY', 'DAY'), ('GTC - Good til Cancelled', 'GTC - Good til Cancelled')])),
                ('order_type_details', models.JSONField(validators=[api.models.validate_order_type_details])),
            ],
        ),
    ]
