name: Monthly Update

# Run on a schedule
on:
  schedule:
    # Every month on the 4th business day at 9 AM UTC
    # Note: GitHub cron uses UTC
    - cron: '0 9 4 * *'  
  workflow_dispatch:  # allows manual triggering

jobs:
  update_indicators:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # or your version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run management command
        env:
          DJANGO_SETTINGS_MODULE: myproject.settings
        run: |
          python manage.py cleanup_old_data